all: verify

verify:
	/mnt/c/Users/Szymon/Desktop/Folders/Embedded\ Software/uppaal-tiga-0.17/bin-Linux/verifytga -w 0 -c -s /mnt/c/Users/Szymon/Desktop/Git/F410-Electric-Bike-Project/uppaal/uppaal_project.xml /mnt/c/Users/Szymon/Desktop/Git/F410-Electric-Bike-Project/uppaal/uppaal_project.q